# NOTE: To be safe, use spaces, not tabs
# Experimental Design Parameters
num_stimuli: 37
overlap: 2 # do not change unless necessary - controls size of overlapping set of stimuli across two trials
num_stimuli_per_trial: 8
path_to_stimulus_list: '/Users/suniyya/Dropbox/Research/Thesis_Work/Psychophysics_Aim1/similarities/experiments/word_exp/stimuli.txt'
# Modeling Parameters
sigmas: 1
max_trials: 5994
model_dimensions: [1, 2, 3, 4, 5]
num_repeats: 5
epsilon: 1e-30
minimization: 'gradient-descent'
tolerance: 1e-6
fatol: 1e-5
max_iterations: 5000
learning_rate: 0.05 # was 0.01
# Non-Euclidean Parameters
curvature: 1
hyperbolic: False
spherical: True
